/* ------------------------------------------------------------------------
   LOOP CITY - combined app v1
   nodes_fixed.js   the seventeen stations, in every grid the app uses.

   GENERATED by build/build_nodes.py on 2026-09-20. Do not hand-edit:
   re-run the build instead, or the two models drift apart again.

   Why this file exists. The growth model reads nodes.csv, whose stations were
   snapped onto the railway alignment that was actually drawn. The mould carried
   the nominal positions baked into the base-map metadata, which predate the
   alignment. They differ by up to a few hundred metres. Fabric grown around one
   set and roads routed around the other give parcels that do not close on their
   stations, which is the one thing the combined drawing is for. The snapped
   positions win, because that is where the railway is. Both models read THIS.

   The trap this file avoids. The base map records mPerPx: 35.0. It is not 35.
   The sheet is 2513 px across 87,985.6 m (35.0122 m) and 2288 px down 80,111.6 m
   (35.0138 m). Rounding to 35 leans the whole sheet by about a pixel at the far
   edge - roughly 30 m on the ground. Small, but systematic, and it adds to the
   snap shift rather than cancelling it. Every pixel below comes from the extent.
   Likewise the mould's coarse grid is exactly HALF the fine grid (475 x 433),
   not the extent divided by 433, so the two resolutions still nest.

   Coordinates, all of them, share one convention: x grows east from E0, y grows
   DOWN from N1. Cell coordinates are fractional on purpose - a station sits
   somewhere inside a cell, and rounding it to the cell centre here would throw
   away up to half a cell (46 m in the mould, 35 m in growth), which is the same
   order as the drift we just spent this file removing.
   ------------------------------------------------------------------------ */

(function (global) {
  'use strict';

  // The corners. Everything else is derived from these four numbers.
  var E0 = 452754.1, E1 = 540739.7, N0 = 166381.6, N1 = 246493.2;

  var META = {
    crs: 'EPSG:27700',
    built: '2026-09-20',
    source: 'assets/nodes.csv (snapped) + assets/Z0506_belt_meta.json (nominal, for comparison only)',
    extentBNG: { e0: 452754.1, e1: 540739.7, n0: 166381.6, n1: 246493.2 },

    // Sheet: the base map raster. mPerPx is derived, NOT the metadata's 35.0.
    sheet:  { w: 2513, h: 2288, mPerPxE: 35.012177, mPerPxN: 35.013811 },

    // Mould fine grid. cellE/cellN are NEVER 92.584 - that figure comes from a
    // different extent and quietly shears the whole registration.
    fine:   { w: 950, h: 865, cellE: 92.616421, cellN: 92.614566 },

    // Mould coarse grid: exactly 2x fine, so a coarse cell is four fine cells.
    // cellE/cellN are filled in below by DOUBLING the fine values rather than
    // written out again here. Two independently rounded literals would differ in
    // the last decimal, and the one relationship this grid has to hold is that it
    // is exactly twice the other - so the code says so instead of hoping.
    coarse: { w: 475, h: 433, cellE: 0, cellN: 0 },

    // Growth: the modelled window, exactly 70 m a cell by definition.
    growth: { w: 1256, h: 1144, step: 70, fullW: 2143, fullH: 1757 },

    // Road widths, set by the user on 20 Sep. Internal roads are not this app's
    // job - they come later out of parcel subdivision with the wool thread.
    roadWidthM: { main: 35, secondary: 19 },

    note: 'Positions are SNAPPED to the built alignment. shiftM is how far each moved from nominal.'
  };

  META.coarse.cellE = META.fine.cellE * 2;
  META.coarse.cellN = META.fine.cellN * 2;

  // ---------------------------------------------------------------- converters
  // Kept here rather than in the consumers so there is exactly one place where a
  // BNG coordinate becomes a cell, and one place to be wrong.
  function bngToSheet(e, n)  { return { x: (e - E0) / META.sheet.mPerPxE, y: (N1 - n) / META.sheet.mPerPxN }; }
  function bngToFine(e, n)   { return { x: (e - E0) / META.fine.cellE,    y: (N1 - n) / META.fine.cellN }; }
  function bngToCoarse(e, n) { return { x: (e - E0) / META.coarse.cellE,  y: (N1 - n) / META.coarse.cellN }; }
  function bngToGrowth(e, n) { return { x: (e - E0) / META.growth.step,   y: (N1 - n) / META.growth.step }; }

  // A node on the far frame line counts as outside, matching how the raster is
  // indexed 0..w-1. Half a pixel decides it, so it is written down once.
  function inQuadrant(sx, sy) {
    return sx >= 0 && sx < META.sheet.w && sy >= 0 && sy < META.sheet.h;
  }

  // ------------------------------------------------------------------- the data
  var NODES = [
    { id: 'P1', kind: 'P', E: 473624.174, N: 218688.073,
      sheetX: 596.080452, sheetY: 794.118825, fineX: 225.33881, fineY: 300.224119,
      growthX: 298.143916, growthY: 397.216094, chainageM: 0,
      inZone: true, shiftM: 37.71, shiftFromMouldM: 28.38, vertexIndex: 0 },
    { id: 'S1', kind: 'S', E: 496680.483, N: 230268.055,
      sheetX: 1254.60303, sheetY: 463.392712, fineX: 474.28288, fineY: 175.18999,
      growthX: 627.519756, growthY: 231.787785, chainageM: 28147,
      inZone: true, shiftM: 318.81, shiftFromMouldM: 316.4, vertexIndex: 1137 },
    { id: 'A3', kind: 'A', E: 511505.452, N: 225491.607,
      sheetX: 1678.026268, sheetY: 599.808819, fineX: 634.351355, fineY: 226.763386,
      growthX: 839.305031, growthY: 300.022753, chainageM: 45531.68,
      inZone: true, shiftM: 10.01, shiftFromMouldM: 16.59, vertexIndex: 1838 },
    { id: 'P2', kind: 'P', E: 518974.738, N: 237670.224,
      sheetX: 1891.360201, sheetY: 251.985593, fineX: 714.998882, fineY: 95.265532,
      growthX: 946.009108, growthY: 126.042514, chainageM: 60654.31,
      inZone: true, shiftM: 126.71, shiftFromMouldM: 144.94, vertexIndex: 2448 },
    { id: 'S2', kind: 'S', E: 541099.066, N: 232761.722,
      sheetX: 2523.264034, sheetY: 392.17319, fineX: 953.880156, fineY: 148.264777,
      growthX: 1262.070945, growthY: 196.163972, chainageM: 86850.96,
      inZone: false, shiftM: 356.49, shiftFromMouldM: 334.99, vertexIndex: 3502 },
    { id: 'A1', kind: 'A', E: 555754.437, N: 224471.098,
      sheetX: 2941.843294, sheetY: 628.954739, fineX: 1112.117441, fineY: 237.782277,
      growthX: 1471.433388, growthY: 314.601464, chainageM: 103876.59,
      inZone: false, shiftM: 71.43, shiftFromMouldM: 87.08, vertexIndex: 4186 },
    { id: 'P3', kind: 'P', E: 569068.261, N: 218381.861,
      sheetX: 3322.105974, sheetY: 802.864291, fineX: 1255.869748, fineY: 303.530425,
      growthX: 1661.630876, growthY: 401.590553, chainageM: 118757.57,
      inZone: false, shiftM: 330.94, shiftFromMouldM: 332.04, vertexIndex: 4784 },
    { id: 'S3', kind: 'S', E: 576170.798, N: 198159.914,
      sheetX: 3524.965005, sheetY: 1380.406326, fineX: 1332.557403, fineY: 521.875643,
      growthX: 1763.095679, growthY: 690.475521, chainageM: 142846.94,
      inZone: false, shiftM: 86.57, shiftFromMouldM: 133.96, vertexIndex: 5754 },
    { id: 'P4', kind: 'P', E: 560766.626, N: 175249.817,
      sheetX: 3084.998888, sheetY: 2034.722305, fineX: 1166.235155, fineY: 769.245976,
      growthX: 1543.036088, growthY: 1017.762609, chainageM: 173033.84,
      inZone: false, shiftM: 18.13, shiftFromMouldM: 60.87, vertexIndex: 6968 },
    { id: 'S4', kind: 'S', E: 571067.336, N: 151554.137,
      sheetX: 3379.202534, sheetY: 2711.474683, fineX: 1277.454201, fineY: 1025.098602,
      growthX: 1690.189088, growthY: 1356.272323, chainageM: 199048.57,
      inZone: false, shiftM: 340.76, shiftFromMouldM: 362.38, vertexIndex: 8012 },
    { id: 'P5', kind: 'P', E: 540654.25, N: 147388.081,
      sheetX: 2510.559428, sheetY: 2830.457924, fineX: 949.07738, fineY: 1070.081339,
      growthX: 1255.716432, growthY: 1415.787419, chainageM: 246612.18,
      inZone: false, shiftM: 21.2, shiftFromMouldM: 29.38, vertexIndex: 9926 },
    { id: 'A2', kind: 'A', E: 529304.332, N: 141155.923,
      sheetX: 2186.388838, sheetY: 3008.449338, fineX: 826.529804, fineY: 1137.372674,
      growthX: 1093.574747, growthY: 1504.818244, chainageM: 259600.17,
      inZone: false, shiftM: 234.67, shiftFromMouldM: 283.61, vertexIndex: 10448 },
    { id: 'S5', kind: 'S', E: 509181.786, N: 132196.488,
      sheetX: 1611.658887, sheetY: 3264.332222, fineX: 609.262213, fineY: 1234.111614,
      growthX: 806.109796, growthY: 1632.810173, chainageM: 282101.76,
      inZone: false, shiftM: 116.13, shiftFromMouldM: 165.69, vertexIndex: 11352 },
    { id: 'S6', kind: 'S', E: 478761.108, N: 132726.108,
      sheetX: 742.798939, sheetY: 3249.206198, fineX: 280.803419, fineY: 1228.393077,
      growthX: 371.528681, growthY: 1625.244176, chainageM: 315475.23,
      inZone: false, shiftM: 2.98, shiftFromMouldM: 45.84, vertexIndex: 12692 },
    { id: 'P6', kind: 'P', E: 473492.847, N: 154405.884,
      sheetX: 592.329556, sheetY: 2630.028358, fineX: 223.920843, fineY: 994.30705,
      growthX: 296.267815, growthY: 1315.533091, chainageM: 338694.26,
      inZone: false, shiftM: 324.17, shiftFromMouldM: 336.64, vertexIndex: 13626 },
    { id: 'S7', kind: 'S', E: 462065.319, N: 166113.015,
      sheetX: 265.942298, sheetY: 2295.67082, fineX: 100.53529, fineY: 867.900026,
      growthX: 133.01741, growthY: 1148.288352, chainageM: 355420.85,
      inZone: false, shiftM: 128.73, shiftFromMouldM: 147.86, vertexIndex: 14299 },
    { id: 'S8', kind: 'S', E: 465285.902, N: 198205.247,
      sheetX: 357.92697, sheetY: 1379.111604, fineX: 135.308643, fineY: 521.386162,
      growthX: 179.025747, growthY: 689.827905, chainageM: 389977.29,
      inZone: true, shiftM: 225.91, shiftFromMouldM: 216.88, vertexIndex: 15687 }
  ];

  // Lookup by id. Built once; a linear scan seventeen times a frame is free, but
  // a typo'd id returning undefined silently is not, so byId throws on a miss.
  var INDEX = {};
  (function () {
    var i;
    for (i = 0; i < NODES.length; i++) { INDEX[NODES[i].id] = NODES[i]; }
  }());

  function byId(id) {
    var n = INDEX[id];
    if (!n) { throw new Error('nodes_fixed: no station named ' + id); }
    return n;
  }

  // The nodes the mould may seed at. It seeds only inside the quadrant, so this
  // list - not the full seventeen - is what the seeding code should walk.
  function inZoneNodes() {
    var out = [], i;
    for (i = 0; i < NODES.length; i++) { if (NODES[i].inZone) { out.push(NODES[i]); } }
    return out;
  }

  // ------------------------------------------------------------------ selfCheck
  // There is no Node on this machine, so this module has never been executed when
  // it is written. Run window.NODES_META.selfCheck() in the browser console; it
  // returns a plain object and touches nothing. A red line here means the grids
  // have drifted and every drawing built on them is out of register.
  function selfCheck() {
    var checks = [], i, n, s, f, g, bad;

    function ck(name, ok, detail) { checks.push({ name: name, ok: !!ok, detail: detail }); }
    function near(a, b, tol) { return Math.abs(a - b) <= tol; }

    // 1. Synthetic: the north-west corner is the origin of every grid.
    s = bngToSheet(E0, N1); f = bngToFine(E0, N1); g = bngToGrowth(E0, N1);
    ck('corner NW maps to (0,0) in all grids',
       near(s.x, 0, 1e-9) && near(s.y, 0, 1e-9) && near(f.x, 0, 1e-9) &&
       near(f.y, 0, 1e-9) && near(g.x, 0, 1e-9) && near(g.y, 0, 1e-9),
       'sheet ' + s.x.toFixed(6) + ',' + s.y.toFixed(6));

    // 2. Synthetic: the far corner lands exactly on the grid size. This is the
    //    check that fails first if anyone reinstates a flat 35 m.
    s = bngToSheet(E1, N0); f = bngToFine(E1, N0);
    ck('corner SE maps to sheet (w,h) and fine (950,865)',
       near(s.x, META.sheet.w, 1e-3) && near(s.y, META.sheet.h, 1e-3) &&
       near(f.x, META.fine.w, 1e-3) && near(f.y, META.fine.h, 1e-3),
       'sheet ' + s.x.toFixed(3) + ',' + s.y.toFixed(3) + '  fine ' + f.x.toFixed(3) + ',' + f.y.toFixed(3));

    // 3. The rounding trap, stated as a test: 35.0 is wrong, and wrong by enough
    //    to see. If this ever passes at 35, the extent has changed underneath us.
    ck('m/px is NOT a round 35',
       Math.abs(META.sheet.mPerPxE - 35) > 0.005 && Math.abs(META.sheet.mPerPxN - 35) > 0.005,
       'E ' + META.sheet.mPerPxE.toFixed(6) + '  N ' + META.sheet.mPerPxN.toFixed(6) +
       '  flat-35 error at east edge: ' + Math.abs(META.sheet.w - (E1 - E0) / 35).toFixed(2) + ' px');

    // 4. Coarse must be exactly twice fine, and NOT the extent divided by 433.
    //    433 * 2 is 866, one row more than the fine grid's 865, so dividing the
    //    extent by 433 gives a cell that does not nest - the two mould resolutions
    //    then disagree by 0.21 m a cell, which is 92 m by the bottom of the sheet.
    var wrongN = (N1 - N0) / META.coarse.h;
    ck('coarse is exactly 2x fine, not extent/433',
       near(META.coarse.cellE, META.fine.cellE * 2, 1e-9) &&
       near(META.coarse.cellN, META.fine.cellN * 2, 1e-9) &&
       META.coarse.w * 2 === META.fine.w &&
       Math.abs(META.coarse.cellN - wrongN) > 0.1,
       'coarse cellN ' + META.coarse.cellN.toFixed(6) + ' vs the extent/433 mistake ' + wrongN.toFixed(6));

    ck('growth step is exactly 70 m', META.growth.step === 70, String(META.growth.step));

    // 5. Synthetic mid-sheet point: one metre east must move the same fraction of
    //    a cell in every grid. Catches a sign or an axis swap.
    var aE = E0 + 1000, aN = N1 - 1000;
    var p1 = bngToFine(aE, aN), p2 = bngToFine(aE + META.fine.cellE, aN - META.fine.cellN);
    ck('one fine cell east/south advances the index by exactly 1',
       near(p2.x - p1.x, 1, 1e-9) && near(p2.y - p1.y, 1, 1e-9),
       'dx ' + (p2.x - p1.x).toFixed(9) + '  dy ' + (p2.y - p1.y).toFixed(9));

    // 6. Every stored coordinate must be re-derivable from its E,N. If a hand edit
    //    ever creeps in, this is where it shows up.
    bad = [];
    for (i = 0; i < NODES.length; i++) {
      n = NODES[i];
      s = bngToSheet(n.E, n.N); f = bngToFine(n.E, n.N); g = bngToGrowth(n.E, n.N);
      if (!near(s.x, n.sheetX, 1e-4) || !near(s.y, n.sheetY, 1e-4) ||
          !near(f.x, n.fineX, 1e-4) || !near(f.y, n.fineY, 1e-4) ||
          !near(g.x, n.growthX, 1e-4) || !near(g.y, n.growthY, 1e-4)) { bad.push(n.id); }
    }
    ck('stored cells match the stored BNG', bad.length === 0, bad.join(',') || 'all ' + NODES.length + ' agree');

    // 7. inZone must be the bounds test, not a remembered flag from the old metadata.
    bad = [];
    for (i = 0; i < NODES.length; i++) {
      n = NODES[i];
      if (inQuadrant(n.sheetX, n.sheetY) !== n.inZone) { bad.push(n.id); }
    }
    ck('inZone agrees with the sheet bounds', bad.length === 0, bad.join(',') || 'all agree');

    // 8. Ids unique, kinds known, positions finite. Cheap, and it catches a
    //    truncated or half-written generated file immediately.
    bad = []; var seen = {};
    for (i = 0; i < NODES.length; i++) {
      n = NODES[i];
      if (seen[n.id]) { bad.push('dup ' + n.id); }
      seen[n.id] = 1;
      if (n.kind !== 'P' && n.kind !== 'S' && n.kind !== 'A') { bad.push('kind ' + n.id); }
      if (!isFinite(n.E) || !isFinite(n.N) || !isFinite(n.shiftM)) { bad.push('nan ' + n.id); }
    }
    ck('ids unique, kinds P/S/A, numbers finite', bad.length === 0, bad.join(',') || String(NODES.length) + ' nodes');

    // 9. byId throws rather than returning undefined, and the five the brief names
    //    are all present.
    var five = ['P1', 'S1', 'A3', 'P2', 'S8'], missing = [];
    for (i = 0; i < five.length; i++) {
      try { byId(five[i]); } catch (e) { missing.push(five[i]); }
    }
    ck('the five that matter are present', missing.length === 0, missing.join(',') || five.join(' '));
    var threw = false;
    try { byId('NOT_A_STATION'); } catch (e2) { threw = true; }
    ck('byId throws on an unknown id', threw, threw ? 'throws' : 'returned silently');

    var fails = 0;
    for (i = 0; i < checks.length; i++) { if (!checks[i].ok) { fails++; } }
    return {
      pass: fails === 0,
      failed: fails,
      ran: checks.length,
      nodes: NODES.length,
      inZone: inZoneNodes().length,
      checks: checks
    };
  }

  META.bngToSheet = bngToSheet;
  META.bngToFine = bngToFine;
  META.bngToCoarse = bngToCoarse;
  META.bngToGrowth = bngToGrowth;
  META.inQuadrant = inQuadrant;
  META.byId = byId;
  META.inZoneNodes = inZoneNodes;
  META.selfCheck = selfCheck;

  global.NODES = NODES;
  global.NODES_META = META;
}(this));
